config/routes.rb
TaskManager::Application.routes.draw do
  devise_for :users
  resources :users, :only => [:index, :show, :destroy]

  resources :projects

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :project
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all.paginate

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.paginate

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end
  
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My projets</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => false %>
  <%= javascript_include_tag :defaults, :cache => false %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">My projets</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
       <% if user_signed_in? %>
          <li>Signed in as <%= current_user.email %>. Not you? <a href="<%= destroy_user_session_path %>" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
       <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => "logout" %> or <%= link_to "Sign in", new_user_session_path, :class => "logout" %></li>
       <% end %>
          
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
          <li class="<%= controller_name == "projects" ? 'active' : '' %>"><%= link_to "Projects", projects_path %></li>
          <li class="<%= controller_name == "users" ? 'active' : '' %>"><%= link_to "Users", users_path %></li>
       </ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> My projets.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/projects/_form.html.erb
  <div class="group">
    <%= f.label :user, t("activerecord.attributes.project.user", :default => ""), :class => :label %>
    <%= f.select :user_id, User.all.collect { |u| [u.email, u.id]}, {:include_blank => '-'} %>
  </div>

  <div class="group">
    <%= f.label :title, t("activerecord.attributes.project.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.project.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>  
  <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + " " + t("web-app-theme.cancel", :default => "Cancel"), projects_path, :class => "button" %> 
</div>

app/views/projects/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", projects_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_project_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_project_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Project</h2>
    <div class="inner">
      <%= form_for @project, :url => project_path(@project), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/projects/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", projects_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_project_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Projects</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">User</th>
                    <th>
            <%= t("activerecord.attributes.project.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @projects.each do |project| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= project.user.nil? ? "" : project.user.email %>
          </td>
                    <td>
            <%= link_to project.title, project_path(project) %>
          </td>
                    <td>
            <%= project.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", project_path(project) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_project_path(project) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", project_path(project), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= will_paginate @projects  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/projects/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", projects_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_project_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Project</h2>
    <div class="inner">
      <%= form_for :project, :url => projects_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/projects/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", projects_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_project_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", project_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.project.user.email", :default => t("activerecord.labels.title", :default => "User")) %>:</b>
          <%= @project.user.nil? ? "" : @project.user.email %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.project.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @project.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.project.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @project.description %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_project_path(@project), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), project_path(@project), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/users/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/users/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", users_path  %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Users</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.user.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @users.each do |user| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= user.id %>
          </td>
                    <td>
            <%= link_to user.email, user_path(user) %>
          </td>
                    <td>
            <%= user.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", user_path(user) %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= will_paginate @users  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/users/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li><%= link_to "#{t("web-app-theme.list", :default => "List")}", users_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", user_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Title")) %>:</b>
          <%= @user.email %>
        </p>

      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), user_path(@user), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>